(test (eval (app (fun 'x (add (id 'x) (num 1))) (num 2)) empty-env) (numV 3))(test (eval (num 42) empty-env) (numV 42))
(test (eval (add (num 2) (num 3)) empty-env) (numV 5))
(test (eval (sub (num 5) (num 3)) empty-env) (numV 2))
(test (eval (mul (num 2) (num 4)) empty-env) (numV 8))
(test (eval tt empty-env) (boolV #t))
(test (eval ff empty-env) (boolV #f))
(test (eval (leq (num 3) (num 5)) empty-env) (boolV #t))
(test (eval (ifc (leq (num 3) (num 5)) (num 2) (num 4)) empty-env) (numV 2))
(test (eval (fun 'x (add (id 'x) (num 1))) empty-env) (closureV 'x (add (id 'x) (num 1)) empty-env))
(test (eval (app (fun 'x (add (id 'x) (num 1))) (num 2)) empty-env) (numV 3))
(test (eval (app (fun 'x (add (id 'x) (id 'x))) (num 2)) empty-env) (numV 4))
(test (eval (app (fun 'x (add (id 'x) (id 'y))) (num 2)) (extend-env 'y (numV 3) empty-env)) (numV 5))
(test (eval (app (fun 'x (add (id 'x) (id 'y))) (num 2)) (extend-env 'z (numV 3) (extend-env 'y (numV 4) empty-env))) (error 'env-lookup "free identifier: y"))
(test (eval (app (fun 'x (add (id 'x) (id 'y))) (num 2)) (extend-env 'y (numV 3) (extend-env 'x (numV 4) empty-env))) (numV 5))
(test (eval (app (fun 'x (add (id 'x) (id 'y))) (num 2)) (extend-env 'y (boolV #t) (extend-env 'x (numV 4) empty-env))) (error "num-op: invalid operands "))
(test (eval (app (fun 'x (add (id 'x) (id 'y))) (num 2)) (extend-env 'y (numV 3) (extend-env 'x (boolV #t) empty-env))) (error "num-op: invalid operands "))
(test (eval (tupl (list (num 1) (num 2) (num 3))) empty-env) (tupl (list (numV 1) (numV 2) (numV 3))))
(test (eval (app (id '+) (list (num 2) (num 3))) empty-env) (numV 5))
(test (eval (app (id 'my-function) (list (num 2) (num 3) (num 4))) (extend-env 'my-function (fun 'x (add (id 'x) (id 'y))) empty-env)) (error 'env-lookup "free identifier: y"))